[Task #80844] Improve search function to be able to apply on filtered…
awesome-academy/NAITEI-PHP-BATCH2-T7 pull request #50
Opened 2024-09-09 09:05 UTC by minhsieu9102003

ready 

https://edu-redmine.sun-asterisk.vn/issues/80844

2024-09-10 04:18 UTC, tuan-bach123 requested changes
Doi nhieu file qua r a

2024-09-11 14:18 UTC, yamada5131 commented
close plz

2024-09-13 03:40 UTC, tuan-bach123 approved these changes

2024-09-13 03:40 UTC, tuan-bach123 commented on ecommerce-app/app/Http/Controllers/CartController.php
> +            return view("cart.show", ["cart" => $cart, "order_items" => null]);
Ko co view nao la cart.show dau

2024-09-13 03:40 UTC, tuan-bach123 commented on ecommerce-app/routes/web.php
> -    Route::delete('/cart/removeItem', [CartController::class, 'removeItem'])->name('cart.removeItem');
check lai xem a van xoa het route cart cua e nay

2024-09-13 03:44 UTC, notverygood135 approved these changes

2024-09-13 04:04 UTC, yamada5131 approved these changes

2024-09-13 04:08 UTC, thinhnv-2059 approved these changes

2024-09-13 04:08 UTC, merged